version: '3'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
    environment:
      - discovery.type=single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
  kibana:
    links:
      - es
    image: docker.elastic.co/kibana/kibana-oss:6.2.4
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_URL: http://es:9200
    ports:
      - "5601:5601"
  web:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    environment:
      - FLASK_APP=webcompat_search:create_app
      - SECRET_KEY=unique-snowflake
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    links:
      - es

volumes:
  esdata:
    driver: local
