version: '3'
services:
  web:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    environment:
      - FLASK_APP=webcompat_domains:create_app
      - SECRET_KEY=unique-snowflake
    ports:
      - "5000:5000"
    volumes:
      - .:/code
