version: '3'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.2
    environment:
      - discovery.type=single-node
  s3:
    image: andrewgaul/s3proxy
    environment:
      - S3PROXY_AUTHORIZATION=none
  web:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    environment:
      - FLASK_APP=webcompat_domains:create_app
      - SECRET_KEY=unique-snowflake
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    links:
      - es
      - s3
